# Generated by Django 4.0.3 on 2023-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livro', '0002_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
    ]
