# Generated by Django 4.0.3 on 2023-06-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livro', '0004_livro_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Quant_leituras',
            field=models.IntegerField(default=0),
        ),
    ]
