# Generated by Django 4.0.3 on 2023-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livro', '0005_livro_quant_leituras'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Sinopse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
