# Generated by Django 4.0.3 on 2023-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leitura', '0002_alter_leitura_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='Favorito',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
