# Generated by Django 4.0.3 on 2023-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_alter_perfil_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Bio',
            field=models.TextField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Cidade',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Estado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/fotoUsuario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
