# Generated by Django 4.0.3 on 2023-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Data_nascimento',
            field=models.DateField(),
        ),
    ]
