# Generated by Django 4.0.3 on 2023-06-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leitura', '0005_alter_leitura_data_final_alter_leitura_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='Avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
