# Generated by Django 4.0.3 on 2023-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leitura', '0007_alter_leitura_data_final_alter_leitura_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='Meta_leitura',
            field=models.CharField(blank=True, choices=[('Esse mês', 'Esse mês'), ('Próximo mês', 'Próximo mês'), ('Esse ano', 'Esse ano'), ('Próximo ano', 'Próximo ano'), ('Não sei', 'Não sei')], max_length=1000, null=True),
        ),
    ]
