# Generated by Django 4.0.3 on 2023-04-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/'),
        ),
    ]
