# Generated by Django 4.0.3 on 2023-04-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livro', '0003_alter_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='is_valid',
            field=models.BooleanField(default='False'),
        ),
    ]
