# Generated by Django 4.0.3 on 2023-05-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_perfil_bio_perfil_cidade_perfil_estado_perfil_genero_and_more'),
        ('Livro', '0004_livro_is_valid'),
        ('Comentario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Comentario',
        ),
    ]
