# Generated by Django 4.0.3 on 2023-05-29 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Comentario', '0002_rename_mensagem_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='Data_criaçao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
